name: "Container image build"

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 10 1 */3 *'

jobs:
  image:
    env:
      IMAGE_NAME: gtfstidy

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: patrickbr/gtfstidy
          ref: main
      - name: Use Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
          save-config: true
          export-config: true
          version: v2.24.0
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_ORGANIZATION_ID }}
      - name: Login to Scaleway Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_PUSH_REGISTRY }}
          username: ${{ vars.DOCKER_PUSH_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_PUSH_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value={{date 'YYYY-MM-DDTHH-mm'}}
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}