on:
  push

permissions:
    contents: write
    packages: write

jobs:
  container-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        go mod init gtfstidy
        go mod tidy
        go build .
    - run: |
        echo "VERSION=$(date +%Y-%m-%dT%H-%M)" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: lehrenfried/gtfstidy:latest,lehrenfried/gtfstidy:${{ env.VERSION }}
